name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Copy deploy.sh to server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ./scripts/deploy.sh $DEPLOY_USER@$DEPLOY_HOST:/home/${DEPLOY_USER}/fastapi-book-project/scripts/deploy.sh

      - name: Run deploy.sh on server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "chmod +x /home/${DEPLOY_USER}/fastapi-book-project/scripts/deploy.sh && /home/${DEPLOY_USER}/fastapi-book-project/scripts/deploy.sh"